# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependency
        run: npm install
      - name: Copy .env
        run: copy('.env.example', '.env');
      - name: Init testing
        run: |
          node ace test
        env:
          CI: true
